[2024-11-30 14:38:20,264] [DEBUG] [main.py:23] This message should go to the log file
[2024-11-30 14:38:20,264] [INFO] [main.py:24] So should this
[2024-11-30 14:38:20,264] [WARNING] [main.py:25] And this, too
[2024-11-30 14:38:20,264] [ERROR] [main.py:26] And non-ASCII stuff, too, like Øresund and Malmö
[2024-11-30 14:38:20,265] [ERROR] [main.py:35] mainでエラーを捕捉した!
Traceback (most recent call last):
  File "/Users/dgmr2/programming/debugger/Notebook/logger/main.py", line 30, in main
    result = culc_div(1, 0)
  File "/Users/dgmr2/programming/debugger/Notebook/logger/mymodule.py", line 35, in culc_div
    result = num1 / num2
ZeroDivisionError: division by zero
